### ISSUE TITLE
bug: `vtsls` crashes when `lang.vue` extra is enabled without `lang.typescript`

### ISSUE THREAD

**Issue by sebastae** [LazyVim/LazyVim#3398]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Kubuntu 24.04

### Describe the bug

When the `lang.vue` extra is enabled without `lang.typescript` the server crashes with the message `Client <x> quit with exit code 1 and signal 0`.

<details>
<summary>:LspLog entry</summary>
<pre>[ERROR][2024-05-31 12:41:14] .../vim/lsp/rpc.lua:734	"rpc"	"/home/sebastian/.local/share/nvim/mason/bin/vtsls"	"stderr"	"/home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:14757
        for (const plugin of configPlugins) {
                             ^

TypeError: configPlugins is not iterable
    at PluginManager.readPlugins (/home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:14757:30)
    at get plugins [as plugins] (/home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:14744:32)
    at TypeScriptServiceClientHost.getAllModeIds (/home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:13807:28)
    at new TypeScriptServiceClientHost (/home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:13735:33)
    at _LazyValue._getValue (/home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:13935:24)
    at get value [as value] (/home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:655:30)
    at /home/sebastian/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist/index.js:13948:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)

Node.js v20.9.0
<pre>
</details>

This is most likely a result of the conversion to list from config object only happens in the `lang.typescript` extra as a result of  cf6775a

### Steps To Reproduce

1. Enable the `lang.vue` extra, but NOT `lang.typescript` 
2. Restart NeoVim
3. Open any `.vue` / `.js` / `.ts` file

### Expected Behavior

The `vtsls` server starts without issue

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	"folke/LazyVim",
	spec = {
		{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
		{ import = "lazyvim.plugins.extras.lang.vue" },
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
You need to have the typescritp extra enabled in order for vue to work correctly.
Will make sure its always enabled when selecting vue

**Comment by folke** [comment]
maybe better to change it so it doesnt do the config object thing...

**Comment by sebastae** [comment]
Simply deleting the `vue =` part of the config seems to work

```diff
diff --git a/lua/lazyvim/plugins/extras/lang/vue.lua b/lua/lazyvim/plugins/extras/lang/vue.lua
index dfc1d2f..36bac9a 100644
--- a/lua/lazyvim/plugins/extras/lang/vue.lua
+++ b/lua/lazyvim/plugins/extras/lang/vue.lua
@@ -32,7 +32,7 @@ return {
               tsserver = {
                 globalPlugins = {
                   -- Use typescript language server along with vue typescript plugin
-                  vue = {
+                  {
                     name = "@vue/typescript-plugin",
                     location = vue_typescript_plugin,
                     languages = { "vue" },
```

Although I don't know enough of the internals to know if this breaks something somewhere else
