### ISSUE TITLE
bug: vtsls error when using code actions

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#3763]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux

### Describe the bug

Prompts an error when using Code Actions in `.tsx` or `.jsx` files.
- This is the error : 
`  [Fzf-lua] "codeAction/resolve" failed with error -32603: Request codeAction/resolve failed with message: <sema 
 antic> TypeScript Server Error (5.4.5) 
 Debug Failure. Expected isNewFile for (only) new files. {"isNewFile":true,"hasScriptInfo":true} 
 Error: Debug Failure. Expected isNewFile for (only) new files. {"isNewFile":true,"hasScriptInfo":true} 
 at IpcIOSession.mapTextChangeToCodeEdit (/home/redox/Code/Experiments/next-nightwatch/node_modules/typescr 
 ript/lib/tsserver.js:187338:13) 
 at /home/redox/Code/Experiments/next-nightwatch/node_modules/typescript/lib/tsserver.js:187330:46 
 at Array.map (<anonymous>) 
 at IpcIOSession.mapTextChangesToCodeEdits (/home/redox/Code/Experiments/next-nightwatch/node_modules/types 
 script/lib/tsserver.js:187330:25) 
 at IpcIOSession.getEditsForRefactor (/home/redox/Code/Experiments/next-nightwatch/node_modules/typescript/ 
 /lib/tsserver.js:187207:21) 
 at getEditsForRefactor (/home/redox/Code/Experiments/next-nightwatch/node_modules/typescript/lib/tsserver. 
 .js:185408:43) 
 at /home/redox/Code/Experiments/next-nightwatch/node_modules/typescript/lib/tsserver.js:187569:69 
 at IpcIOSession.executeWithRequestId (/home/redox/Code/Experiments/next-nightwatch/node_modules/typescript 
 t/lib/tsserver.js:187561:14) 
 at IpcIOSession.executeCommand (/home/redox/Code/Experiments/next-nightwatch/node_modules/typescript/lib/t 
 tsserver.js:187569:29) 
 at IpcIOSession.onMessage (/home/redox/Code/Experiments/next-nightwatch/node_modules/typescript/lib/tsserv 
 ver.js:187611:51) 
 at process.<anonymous> (/home/redox/Code/Experiments/next-nightwatch/node_modules/typescript/lib/tsserver. 
 .js:189220:14) 
 at process.emit (node:events:519:28) 
 at emit (node:internal/child_process:951:14) 
 at process.processTicksAndRejections (node:internal/process/task_queues:83:21) `
 
 - visually how it looks:
 ![t_2024_06_22_07_36](https://github.com/LazyVim/LazyVim/assets/13983258/ab22bc30-2f92-4f99-8197-84c7d0badc79)

### Steps To Reproduce

1. Open a `.jsx` or `.tsx` file.
2. Run a Code Action

### Expected Behavior

Should not give this error.
Refactoring using the plugin or Code Actions does not really work that good when working with `tsx` or `jsx`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by arthur-mountain** [comment]
@Redoxahmii 
Could you please check your Node version first? You can do this by running `node -v`.

Additionally, please verify if the LSP server is running by checking for any vtsls errors in the `:LspLog`.

The reason for this request is that vtsls uses esbuild and supports up to Node 16. If your Node version is below 16, there may be syntax errors preventing the LSP server from running correctly.
